### ISSUE TITLE
Displayed schedule is incorrect

### ISSUE THREAD

**Issue by akiyosi** [kaakaa/matter-meeting#5]
スラッシュコマンドで実際に社内の Exchange サーバからスケジュールを取得したのですが、内容が正しくないものが表示されてしまいます。
* スケジュールの開示権限は適切に設定しています
* 画像がアップできないのですが、空きスケジュールが全て左にシフトしたような内容です。(ただ、その空きスケジュール状況自体も正しく無さそうです。)

何か原因についてお気づきの点があればご指摘いただけると幸いです。
別途、時間を作ってもう少し詳細な状況を調査いたします。

**Comment by kaakaa** [comment]
9時間分左にずれている（9:00の予定が0:00に表示される）のだとしたら、タイムゾーンが原因かもしれません。

docker composeで動かしている場合、appサービスの環境変数でタイムゾーンが設定できたかと記憶しています。
手元に確認できる環境がないので、確認出来次第連絡します。

**Comment by akiyosi** [comment]
本件、ご指摘の通りコンテナ内タイムゾーンが UTC であったことが原因のようです。(タイムゾーンは最初に私も怪しんだのですが確認不足でした。)
`Dockerfile` に`ENV TZ Asia/Tokyo` を指定すると上手く表示されました。

こちらの社内Exchange では 8:30-17:30 以外が業務時間外指定(グレーアウト) であり、それと通常のスケジュールが OR で草が生成されたために、Outlook上のスケジュール内容とは一見全く違う表示になっていたことが内容が不正に見えた原因でした。

**Comment by kaakaa** [comment]
検証ありがとうございます。
手元でも同じ事象が発生し、タイムゾーンの設定で解消されるのを確認しました。（ローカルで修正したのをコミットしていなかったようです）

タイムゾーンの設定はコンテナ起動時に指定できるよう`docker-compose.yml`の方で指定するよう修正しました。

まだ問題があればreopenしてください。

---

業務時間外の扱いについては、過去には業務時間中のみの草画像を生成していたりもしましたが、業務時間外に打ち合わせを設定することもあるため現状の形になっています。
上手い表示方法が有ればとは思っていますが。
