### ISSUE TITLE
表示時間帯の制限

### ISSUE THREAD

**Issue by akiyosi** [kaakaa/matter-meeting#8]
#5 にて、「過去には業務時間中のみの草画像を生成していた」とのコメントいただいてますが具体的にどのように実装していたのか参考までにご教示頂けないでしょうか。

私の方で src/helpers/ews/availability.js 内の json 加工している箇所等を色々いじってみたのですが、うまく業務時間のみ抽出することができず。。

**Comment by kaakaa** [comment]
過去のことなので記憶が定かではなく、またコミットも残していなかったようなので申し訳ないですが、下記のコードの`time`,`end`の部分で調整していたかと思います。
https://github.com/kaakaa/matter-meeting/blob/master/src/helpers/ews/availability.js#L61

例えば、上記のコードを
```
let dummyTime = moment('2000-01-01 08:00:00');
const dummyEnd = moment('2000-01-02 18:00:00');
```
とすることで、8:00~18:00までの情報が取得できるようになるはずです。

ただ、8:00~18:00までの情報を取得するようにすると、草画像のレイアウトがずれてしまうのでそちらも修正が必要です。
https://github.com/kaakaa/matter-meeting/blob/master/src/helpers/grass.js#L16
現在は、24時間分のデータが入っていることを前提としたテンプレートとなっています。

上手く依存しないようにコーディングできれば良いのですが、そこまではできていません。

**Comment by akiyosi** [comment]
> 例えば、上記のコードを
> 
> let dummyTime = moment('2000-01-01 08:00:00');
> const dummyEnd = moment('2000-01-02 18:00:00');
> とすることで、8:00~18:00までの情報が取得できるようになるはずです。

> ただ、8:00~18:00までの情報を取得するようにすると、草画像のレイアウトがずれてしまうのでそちらも修正が必要です。

やはり、草のレイアウトも調整が必要でしたか。
上記は試したのですがうまく表示されないなと思っていました。

ありがとうございます。いただいたポイントふまえ考えてみます。
